### ISSUE TITLE
Performance in RF4 beta

### ISSUE THREAD

**Issue by jeremymickel** [klaavo/scalingEditTool#7]
Some small issues show up when using Scale Edit Tool in the current RF4 beta.
- Crosshairs don't show up when you drag a point
- Transform command doesn't bring up bounding box

**Comment by klaavo** [comment]
Hi! Thanks! This is a known issue and something that should be fixed in RF, as far as I know. I'll ask and let Fred know.
A workaround: Open a new glyph window, and it works (probably) until you change the tool to something else and come back again. Also, the transform mode works, even though the red rectangle doesn't show up. I know, not very useful. :)

**Comment by klaavo** [comment]
The issues seem to be fixed in the latest build of RF4.
